### ISSUE TITLE
Asking about localisation of AUs

### ISSUE THREAD

**Issue by glmanhtu** [EvelynFan/FAU#3]
Hello,

There are a few questions I would like to ask about your project:

How did you locale the location of each AU?. I see in your source code https://github.com/EvelynFan/FAU/blob/master/datasets.py#L33 there are 3 points of AU 9, but in the figure 2 in your paper https://arxiv.org/abs/2004.09681 saying only 2 central points ? 

As indicated in your paper, DISFA is a heavy imbalance dataset, so, in the training phase, do you apply some sort of balancing for the dataset ? 

There are some frames in the database that the facial landmarks is predicted incorrect (i.e subject SN029, frames 4330~4536, which lead to the location of AU central points incorrect. What do you do with those frames ?

Thanks

**Comment by EvelynFan** [comment]
> Hello,
> 
> There are a few questions I would like to ask about your project:
> 
> How did you locale the location of each AU?. I see in your source code https://github.com/EvelynFan/FAU/blob/master/datasets.py#L33 there are 3 points of AU 9, but in the figure 2 in your paper https://arxiv.org/abs/2004.09681 saying only 2 central points ?
> 
> As indicated in your paper, DISFA is a heavy imbalance dataset, so, in the training phase, do you apply some sort of balancing for the dataset ?
> 
> There are some frames in the database that the facial landmarks is predicted incorrect (i.e subject SN029, frames 4330~4536, which lead to the location of AU central points incorrect. What do you do with those frames ?
> 
> Thanks

Hi, thanks for your questions.

The location of each AU is defined based on the coordinates of facial landmarks, e.g., a midpoint between two landmarks.  Please follow the code, where there are 3 points of AU9. Sorry for the mistake, it should be 3 points in Fig. 2. However, it won't make much difference in the final estimation actually. 

In the training phase,  I didn't balance the dataset. Hence, for some AUs like 5, 15 and 20, the results are not satisfying. 

For the incorrect facial landmarks, I didn't remove the corresponding frames as I thought this was a rare case. But it should be better if you remove those frames.

**Comment by glmanhtu** [comment]
Awesome. Thank you a lot
