### ISSUE TITLE
I didn't find the calculation function of ICC , would you please tell me how you calculated that evaluation indicator? Thanks a lot.

### ISSUE THREAD

**Issue by JasonAnn** [EvelynFan/FAU#6]

**Comment by EvelynFan** [comment]
> _No description provided._
For the ICC implementation, please refer to this:  https://github.com/cosanlab/nltools/blob/master/nltools/data/brain_data.py
We used ICC(3,1), so icc_type = 'icc3'.

**Comment by EvelynFan** [comment]
> > _No description provided._
> > For the ICC implementation, please refer to this:  https://github.com/cosanlab/nltools/blob/master/nltools/data/brain_data.py
> > We used ICC(3,1), so icc_type = 'icc3'.

See https://github.com/cosanlab/nltools/blob/master/nltools/data/brain_data.py
Line 1344

**Comment by JasonAnn** [comment]
It's helpful ,thanks.

**Comment by pengcheng93** [comment]
If the batch is very large, the calculation speed of this ICC is very slow, how do you evaluate it in the experiments?

**Comment by noirmist** [comment]
> > > _No description provided._
> > > For the ICC implementation, please refer to this:  https://github.com/cosanlab/nltools/blob/master/nltools/data/brain_data.py
> > > We used ICC(3,1), so icc_type = 'icc3'.
> 
> See https://github.com/cosanlab/nltools/blob/master/nltools/data/brain_data.py Line 1344

I guess this is the code you mentioned, am I right?
https://github.com/cosanlab/nltools/blob/8f034dbbbb788fc09cda9be3bd26cdf5eb5e421f/nltools/data/brain_data.py#L1551
