### ISSUE TITLE
BP4D database 

### ISSUE THREAD

**Issue by kanghu-bo** [EvelynFan/FAU#7]
Hi，how to share BP4D database ?

**Comment by EvelynFan** [comment]
> Hi，how to share BP4D database ?
To make a request for the data, please contact the authors. See the link below.
http://www.cs.binghamton.edu/~lijun/Research/3DFE/3DFE_Analysis.html

**Comment by EvelynFan** [comment]
> Hi，how to share BP4D database ?

To make a request for the data, please contact the authors. See the link below.
http://www.cs.binghamton.edu/~lijun/Research/3DFE/3DFE_Analysis.html

**Comment by cug-lucifer** [comment]
> > Hi，how to share BP4D database ?
> 
> To make a request for the data, please contact the authors. See the link below.
> http://www.cs.binghamton.edu/~lijun/Research/3DFE/3DFE_Analysis.html

Execuse me. I asked the authors, and he said it needs 400$. But the web said that database can be provided to reseachers.
