### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by adaniefei** [EvelynFan/FAU#8]
Hi Fan,

I was checking the fork of your repository (https://github.com/ZhiwenShao/FAU) and found a pretrained model (invalid link though) is included for the file "demo.py". I would like to ask if you will include the link to this model here?

Thanks~

**Comment by EvelynFan** [comment]
> Hi Fan,
> 
> I was checking the fork of your repository (https://github.com/ZhiwenShao/FAU) and found a pretrained model (invalid link though) is included for the file "demo.py". I would like to ask if you will include the link to this model here?
> 
> Thanks~

Thanks for your interest. A lightweight Pytorch version will be released at https://github.com/EvelynFan/Pytorch-DSR.

**Comment by EvelynFan** [comment]
> Hi Fan,
> 
> I was checking the fork of your repository (https://github.com/ZhiwenShao/FAU) and found a pretrained model (invalid link though) is included for the file "demo.py". I would like to ask if you will include the link to this model here?
> 
> Thanks~

Thanks for your interest. The Pytorch model will be released at https://github.com/EvelynFan/Pytorch-FAU.

**Comment by Xiaocong6** [comment]
> Hi Fan,
> 
> I was checking the fork of your repository (https://github.com/ZhiwenShao/FAU) and found a pretrained model (invalid link though) is included for the file "demo.py". I would like to ask if you will include the link to this model here?
> 
> Thanks~

@adaniefei  hi~The link to the pretrained model cannot be opened. Can you provide a new download link? Thanks a lot!!!
