### ISSUE TITLE
Can you release your model？Thx

### ISSUE THREAD

**Issue by jiangwqcooler** [EvelynFan/FAU#9]

**Comment by EvelynFan** [comment]
> _No description provided._

Thanks for your interest. A lightweight Pytorch version will be released at https://github.com/EvelynFan/Pytorch-DSR.

**Comment by EvelynFan** [comment]
> _No description provided._

Thanks for your interest. The Pytorch model will be released at https://github.com/EvelynFan/Pytorch-FAU.

**Comment by liuyvchi** [comment]
Hi. The shared link is broken. Is the model still opensourece?
